# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ea723b4b36f98e98caef20130844313485ea3c3c9bfc8d9605b83c5b50552908fe19186cd54d7bd435aed2b8fc17a86419984fc4862a6526717aa87c9fa6f099

test:
  secret_key_base: 92a8dbd7c6743deef5a9af537cd9d521a8de57d352dc8be022a41e17071abc6d29ff70b7c4cc55e6b6ad007709cc23a52fec9acb0c91412415fe629a6db79f0d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
